!     -*- f90 -*-
!     This file is autogenerated with f2py (version:1.24.2)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2pywrapmain (N, Np, Nint, u, v, xi, yi, mu, ro, ubn, R&
     &e, XXX, YYY, x_out, y_out, f2py_u_d0, f2py_u_d1, f2py_v_d0, f2py_v&
     &_d1, f2py_xi_d0, f2py_yi_d0, f2py_XXX_d0, f2py_YYY_d0)
                use arrays
                use interp
                use integrate
      integer N
      integer Np
      integer Nint
      real(kind=8) mu
      real(kind=8) ro
      real(kind=8) ubn
      real(kind=8) Re
      integer f2py_u_d0
      integer f2py_u_d1
      integer f2py_v_d0
      integer f2py_v_d1
      integer f2py_xi_d0
      integer f2py_yi_d0
      integer f2py_XXX_d0
      integer f2py_YYY_d0
      real(kind=8) u(f2py_u_d0,f2py_u_d1)
      real(kind=8) v(f2py_v_d0,f2py_v_d1)
      real(kind=8) xi(f2py_xi_d0)
      real(kind=8) yi(f2py_yi_d0)
      real(kind=8) XXX(f2py_XXX_d0)
      real(kind=8) YYY(f2py_YYY_d0)
      real(kind=8) x_out(Np,Nint)
      real(kind=8) y_out(Np,Nint)
      interface
      
            subroutine main(N,Np,Nint,u,v,xi,yi,mu,ro,ubn,Re,XXX,YYY,x_o&
     &ut,y_out) 
                use arrays
                use interp
                use integrate
                integer, intent(in) :: N
                integer, intent(in) :: Np
                integer, intent(in) :: Nint
                real(kind=8), intent(in),dimension(:,:) :: u
                real(kind=8), intent(in),dimension(:,:) :: v
                real(kind=8), intent(in),dimension(:) :: xi
                real(kind=8), intent(in),dimension(:) :: yi
                real(kind=8), intent(IN) :: mu
                real(kind=8), intent(IN) :: ro
                real(kind=8), intent(IN) :: ubn
                real(kind=8), intent(IN) :: Re
                real(kind=rk), intent(in),dimension(:) :: XXX
                real(kind=rk), intent(in),dimension(:) :: YYY
                real(kind=8), intent(out),dimension(Np, Nint) :: x_out
                real(kind=8), intent(out),dimension(Np, Nint) :: y_out
            end subroutine main
      end interface
      call main(N, Np, Nint, u, v, xi, yi, mu, ro, ubn, Re, XXX, YYY, x_&
     &out, y_out)
      end


      
      subroutine f2pyinitarrays(f2pysetupfunc)
      use arrays, only : r8vec_linspace
      external f2pysetupfunc
      call f2pysetupfunc(r8vec_linspace)
      end subroutine f2pyinitarrays

      subroutine f2pywrap_interp_r8_huge (r8_hugef2pywrap)
      use interp, only : r8_huge
      real(kind=8) r8_hugef2pywrap
      r8_hugef2pywrap = r8_huge()
      end subroutine f2pywrap_interp_r8_huge
      subroutine f2pywrap_interp_r8vec_bracket5 (r8vec_bracket5f2pywrap,&
     & nd, xd, xi)
      use interp, only : r8vec_bracket5
      integer(kind=4) nd
      real(kind=8) xi
      real(kind=8) xd(nd)
      integer(kind=4) r8vec_bracket5f2pywrap
      r8vec_bracket5f2pywrap = r8vec_bracket5(nd, xd, xi)
      end subroutine f2pywrap_interp_r8vec_bracket5
      
      subroutine f2pyinitinterp(f2pysetupfunc)
      use interp, only : pwl_interp_2D
      interface 
      subroutine f2pywrap_interp_r8_huge (r8_hugef2pywrap, r8_huge)
      real(kind=8) r8_huge
      real(kind=8) r8_hugef2pywrap
      end subroutine f2pywrap_interp_r8_huge 
      subroutine f2pywrap_interp_r8vec_bracket5 (r8vec_bracket5f2pywrap,&
     & r8vec_bracket5, nd, xd, xi)
      integer(kind=4) r8vec_bracket5
      integer(kind=4) nd
      real(kind=8) xi
      real(kind=8) xd(nd)
      integer(kind=4) r8vec_bracket5f2pywrap
      end subroutine f2pywrap_interp_r8vec_bracket5
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(f2pywrap_interp_r8_huge,f2pywrap_interp_r8vec_b&
     &racket5,pwl_interp_2D)
      end subroutine f2pyinitinterp

      
      subroutine f2pyinitintegrate(f2pysetupfunc)
      use integrate, only : rk4Interp
      external f2pysetupfunc
      call f2pysetupfunc(rk4Interp)
      end subroutine f2pyinitintegrate


