/* File: genPositionmodule.c
 * This file is auto-generated with f2py (version:1.22.4).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Thu Mar 30 01:48:18 2023
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include <Python.h>
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *genPosition_error;
static PyObject *genPosition_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f##_,F##_)
#else
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f,F)
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(genPosition_error,errstring);\
        /*goto capi_fail;*/\
    } else 

/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = genPosition_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}

static int
double_from_pyobj(double* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
        *v = PyFloat_AsDouble(obj);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    tmp = PyNumber_Float(obj);
    if (tmp) {
        *v = PyFloat_AsDouble(tmp);
        Py_DECREF(tmp);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = genPosition_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_WRAPPEDFUNC(main,MAIN)(int*,int*,int*,double*,double*,double*,double*,double*,double*,int*,int*,int*,int*,int*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/************************************ main ************************************/
static char doc_f2py_rout_genPosition_main[] = "\
x_out,y_out = main(N,Np,Nint,u,v,xi,yi)\n\nWrapper for ``main``.\
\n\nParameters\n----------\n"
"N : input int\n"
"Np : input int\n"
"Nint : input int\n"
"u : input rank-2 array('d') with bounds (f2py_u_d0,f2py_u_d1)\n"
"v : input rank-2 array('d') with bounds (f2py_v_d0,f2py_v_d1)\n"
"xi : input rank-1 array('d') with bounds (f2py_xi_d0)\n"
"yi : input rank-1 array('d') with bounds (f2py_yi_d0)\n"
"\nReturns\n-------\n"
"x_out : rank-2 array('d') with bounds (Np,Nint)\n"
"y_out : rank-2 array('d') with bounds (Np,Nint)";
/* extern void F_WRAPPEDFUNC(main,MAIN)(int*,int*,int*,double*,double*,double*,double*,double*,double*,int*,int*,int*,int*,int*,int*); */
static PyObject *f2py_rout_genPosition_main(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,double*,double*,double*,double*,double*,double*,int*,int*,int*,int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int N = 0;
    PyObject *N_capi = Py_None;
    int Np = 0;
    PyObject *Np_capi = Py_None;
    int Nint = 0;
    PyObject *Nint_capi = Py_None;
    double *u = NULL;
    npy_intp u_Dims[2] = {-1, -1};
    const int u_Rank = 2;
    PyArrayObject *capi_u_tmp = NULL;
    int capi_u_intent = 0;
    PyObject *u_capi = Py_None;
    double *v = NULL;
    npy_intp v_Dims[2] = {-1, -1};
    const int v_Rank = 2;
    PyArrayObject *capi_v_tmp = NULL;
    int capi_v_intent = 0;
    PyObject *v_capi = Py_None;
    double *xi = NULL;
    npy_intp xi_Dims[1] = {-1};
    const int xi_Rank = 1;
    PyArrayObject *capi_xi_tmp = NULL;
    int capi_xi_intent = 0;
    PyObject *xi_capi = Py_None;
    double *yi = NULL;
    npy_intp yi_Dims[1] = {-1};
    const int yi_Rank = 1;
    PyArrayObject *capi_yi_tmp = NULL;
    int capi_yi_intent = 0;
    PyObject *yi_capi = Py_None;
    double *x_out = NULL;
    npy_intp x_out_Dims[2] = {-1, -1};
    const int x_out_Rank = 2;
    PyArrayObject *capi_x_out_tmp = NULL;
    int capi_x_out_intent = 0;
    double *y_out = NULL;
    npy_intp y_out_Dims[2] = {-1, -1};
    const int y_out_Rank = 2;
    PyArrayObject *capi_y_out_tmp = NULL;
    int capi_y_out_intent = 0;
    int f2py_u_d0 = 0;
    int f2py_u_d1 = 0;
    int f2py_v_d0 = 0;
    int f2py_v_d1 = 0;
    int f2py_xi_d0 = 0;
    int f2py_yi_d0 = 0;
    static char *capi_kwlist[] = {"N","Np","Nint","u","v","xi","yi",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOO|:genPosition.main",\
        capi_kwlist,&N_capi,&Np_capi,&Nint_capi,&u_capi,&v_capi,&xi_capi,&yi_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable N */
        f2py_success = int_from_pyobj(&N,N_capi,"genPosition.main() 1st argument (N) can't be converted to int");
    if (f2py_success) {
    /* Processing variable Np */
        f2py_success = int_from_pyobj(&Np,Np_capi,"genPosition.main() 2nd argument (Np) can't be converted to int");
    if (f2py_success) {
    /* Processing variable Nint */
        f2py_success = int_from_pyobj(&Nint,Nint_capi,"genPosition.main() 3rd argument (Nint) can't be converted to int");
    if (f2py_success) {
    /* Processing variable xi */
    ;
    capi_xi_intent |= F2PY_INTENT_IN;
    capi_xi_tmp = array_from_pyobj(NPY_DOUBLE,xi_Dims,xi_Rank,capi_xi_intent,xi_capi);
    if (capi_xi_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : genPosition_error,"failed in converting 6th argument `xi' of genPosition.main to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        xi = (double *)(PyArray_DATA(capi_xi_tmp));

    /* Processing variable yi */
    ;
    capi_yi_intent |= F2PY_INTENT_IN;
    capi_yi_tmp = array_from_pyobj(NPY_DOUBLE,yi_Dims,yi_Rank,capi_yi_intent,yi_capi);
    if (capi_yi_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : genPosition_error,"failed in converting 7th argument `yi' of genPosition.main to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        yi = (double *)(PyArray_DATA(capi_yi_tmp));

    /* Processing variable u */
    ;
    capi_u_intent |= F2PY_INTENT_IN;
    capi_u_tmp = array_from_pyobj(NPY_DOUBLE,u_Dims,u_Rank,capi_u_intent,u_capi);
    if (capi_u_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : genPosition_error,"failed in converting 4th argument `u' of genPosition.main to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        u = (double *)(PyArray_DATA(capi_u_tmp));

    /* Processing variable v */
    ;
    capi_v_intent |= F2PY_INTENT_IN;
    capi_v_tmp = array_from_pyobj(NPY_DOUBLE,v_Dims,v_Rank,capi_v_intent,v_capi);
    if (capi_v_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : genPosition_error,"failed in converting 5th argument `v' of genPosition.main to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        v = (double *)(PyArray_DATA(capi_v_tmp));

    /* Processing variable x_out */
    x_out_Dims[0]=Np,x_out_Dims[1]=Nint;
    capi_x_out_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    capi_x_out_tmp = array_from_pyobj(NPY_DOUBLE,x_out_Dims,x_out_Rank,capi_x_out_intent,Py_None);
    if (capi_x_out_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : genPosition_error,"failed in converting hidden `x_out' of genPosition.main to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        x_out = (double *)(PyArray_DATA(capi_x_out_tmp));

    /* Processing variable y_out */
    y_out_Dims[0]=Np,y_out_Dims[1]=Nint;
    capi_y_out_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    capi_y_out_tmp = array_from_pyobj(NPY_DOUBLE,y_out_Dims,y_out_Rank,capi_y_out_intent,Py_None);
    if (capi_y_out_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : genPosition_error,"failed in converting hidden `y_out' of genPosition.main to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        y_out = (double *)(PyArray_DATA(capi_y_out_tmp));

    /* Processing variable f2py_u_d0 */
    f2py_u_d0 = shape(u, 0);
    /* Processing variable f2py_u_d1 */
    f2py_u_d1 = shape(u, 1);
    /* Processing variable f2py_v_d0 */
    f2py_v_d0 = shape(v, 0);
    /* Processing variable f2py_v_d1 */
    f2py_v_d1 = shape(v, 1);
    /* Processing variable f2py_xi_d0 */
    f2py_xi_d0 = shape(xi, 0);
    /* Processing variable f2py_yi_d0 */
    f2py_yi_d0 = shape(yi, 0);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(&N,&Np,&Nint,u,v,xi,yi,x_out,y_out,&f2py_u_d0,&f2py_u_d1,&f2py_v_d0,&f2py_v_d1,&f2py_xi_d0,&f2py_yi_d0);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("NN",capi_x_out_tmp,capi_y_out_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable f2py_yi_d0 */
    /* End of cleaning variable f2py_xi_d0 */
    /* End of cleaning variable f2py_v_d1 */
    /* End of cleaning variable f2py_v_d0 */
    /* End of cleaning variable f2py_u_d1 */
    /* End of cleaning variable f2py_u_d0 */
    }  /*if (capi_y_out_tmp == NULL) ... else of y_out*/
    /* End of cleaning variable y_out */
    }  /*if (capi_x_out_tmp == NULL) ... else of x_out*/
    /* End of cleaning variable x_out */
    if((PyObject *)capi_v_tmp!=v_capi) {
        Py_XDECREF(capi_v_tmp); }
    }  /*if (capi_v_tmp == NULL) ... else of v*/
    /* End of cleaning variable v */
    if((PyObject *)capi_u_tmp!=u_capi) {
        Py_XDECREF(capi_u_tmp); }
    }  /*if (capi_u_tmp == NULL) ... else of u*/
    /* End of cleaning variable u */
    if((PyObject *)capi_yi_tmp!=yi_capi) {
        Py_XDECREF(capi_yi_tmp); }
    }  /*if (capi_yi_tmp == NULL) ... else of yi*/
    /* End of cleaning variable yi */
    if((PyObject *)capi_xi_tmp!=xi_capi) {
        Py_XDECREF(capi_xi_tmp); }
    }  /*if (capi_xi_tmp == NULL) ... else of xi*/
    /* End of cleaning variable xi */
    } /*if (f2py_success) of Nint*/
    /* End of cleaning variable Nint */
    } /*if (f2py_success) of Np*/
    /* End of cleaning variable Np */
    } /*if (f2py_success) of N*/
    /* End of cleaning variable N */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************** end of main ********************************/

/******************************* r8vec_linspace *******************************/
static char doc_f2py_rout_genPosition_arrays_r8vec_linspace[] = "\
r8vec_linspace(a,b,x,[n])\n\nWrapper for ``r8vec_linspace``.\
\n\nParameters\n----------\n"
"a : input float\n"
"b : input float\n"
"x : input rank-1 array('d') with bounds (n)\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: shape(x, 0)";
/*  */
static PyObject *f2py_rout_genPosition_arrays_r8vec_linspace(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int n = 0;
    PyObject *n_capi = Py_None;
    double a = 0;
    PyObject *a_capi = Py_None;
    double b = 0;
    PyObject *b_capi = Py_None;
    double *x = NULL;
    npy_intp x_Dims[1] = {-1};
    const int x_Rank = 1;
    PyArrayObject *capi_x_tmp = NULL;
    int capi_x_intent = 0;
    PyObject *x_capi = Py_None;
    static char *capi_kwlist[] = {"a","b","x","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOO|O:genPosition.arrays.r8vec_linspace",\
        capi_kwlist,&a_capi,&b_capi,&x_capi,&n_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable a */
        f2py_success = double_from_pyobj(&a,a_capi,"genPosition.arrays.r8vec_linspace() 1st argument (a) can't be converted to double");
    if (f2py_success) {
    /* Processing variable b */
        f2py_success = double_from_pyobj(&b,b_capi,"genPosition.arrays.r8vec_linspace() 2nd argument (b) can't be converted to double");
    if (f2py_success) {
    /* Processing variable x */
    ;
    capi_x_intent |= F2PY_INTENT_IN;
    capi_x_tmp = array_from_pyobj(NPY_DOUBLE,x_Dims,x_Rank,capi_x_intent,x_capi);
    if (capi_x_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : genPosition_error,"failed in converting 3rd argument `x' of genPosition.arrays.r8vec_linspace to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        x = (double *)(PyArray_DATA(capi_x_tmp));

    /* Processing variable n */
    if (n_capi == Py_None) n = shape(x, 0); else
        f2py_success = int_from_pyobj(&n,n_capi,"genPosition.arrays.r8vec_linspace() 1st keyword (n) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(x, 0) == n,"shape(x, 0) == n","1st keyword n","r8vec_linspace:n=%d",n) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&n,&a,&b,x);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*CHECKSCALAR(shape(x, 0) == n)*/
    } /*if (f2py_success) of n*/
    /* End of cleaning variable n */
    if((PyObject *)capi_x_tmp!=x_capi) {
        Py_XDECREF(capi_x_tmp); }
    }  /*if (capi_x_tmp == NULL) ... else of x*/
    /* End of cleaning variable x */
    } /*if (f2py_success) of b*/
    /* End of cleaning variable b */
    } /*if (f2py_success) of a*/
    /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*************************** end of r8vec_linspace ***************************/

/********************************** r8_huge **********************************/
static char doc_f2py_rout_genPosition_interp_r8_huge[] = "\
r8_huge = r8_huge()\n\nWrapper for ``r8_huge``.\
\n\nReturns\n-------\n"
"r8_huge : float";
/* #declfortranroutine# */
static PyObject *f2py_rout_genPosition_interp_r8_huge(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double r8_huge = 0;
    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:genPosition.interp.r8_huge",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
    /* Processing variable r8_huge */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(&r8_huge);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("d",r8_huge);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable r8_huge */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of r8_huge *******************************/

/******************************* r8vec_bracket5 *******************************/
static char doc_f2py_rout_genPosition_interp_r8vec_bracket5[] = "\
r8vec_bracket5 = r8vec_bracket5(xd,xi,[nd])\n\nWrapper for ``r8vec_bracket5``.\
\n\nParameters\n----------\n"
"xd : input rank-1 array('d') with bounds (nd)\n"
"xi : input float\n"
"\nOther Parameters\n----------------\n"
"nd : input int, optional\n    Default: shape(xd, 0)\n"
"\nReturns\n-------\n"
"r8vec_bracket5 : int";
/* #declfortranroutine# */
static PyObject *f2py_rout_genPosition_interp_r8vec_bracket5(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int r8vec_bracket5 = 0;
    int nd = 0;
    PyObject *nd_capi = Py_None;
    double *xd = NULL;
    npy_intp xd_Dims[1] = {-1};
    const int xd_Rank = 1;
    PyArrayObject *capi_xd_tmp = NULL;
    int capi_xd_intent = 0;
    PyObject *xd_capi = Py_None;
    double xi = 0;
    PyObject *xi_capi = Py_None;
    static char *capi_kwlist[] = {"xd","xi","nd",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|O:genPosition.interp.r8vec_bracket5",\
        capi_kwlist,&xd_capi,&xi_capi,&nd_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable r8vec_bracket5 */
    /* Processing variable xd */
    ;
    capi_xd_intent |= F2PY_INTENT_IN;
    capi_xd_tmp = array_from_pyobj(NPY_DOUBLE,xd_Dims,xd_Rank,capi_xd_intent,xd_capi);
    if (capi_xd_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : genPosition_error,"failed in converting 1st argument `xd' of genPosition.interp.r8vec_bracket5 to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        xd = (double *)(PyArray_DATA(capi_xd_tmp));

    /* Processing variable xi */
        f2py_success = double_from_pyobj(&xi,xi_capi,"genPosition.interp.r8vec_bracket5() 2nd argument (xi) can't be converted to double");
    if (f2py_success) {
    /* Processing variable nd */
    if (nd_capi == Py_None) nd = shape(xd, 0); else
        f2py_success = int_from_pyobj(&nd,nd_capi,"genPosition.interp.r8vec_bracket5() 1st keyword (nd) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(xd, 0) == nd,"shape(xd, 0) == nd","1st keyword nd","r8vec_bracket5:nd=%d",nd) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(&r8vec_bracket5,&nd,xd,&xi);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("i",r8vec_bracket5);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*CHECKSCALAR(shape(xd, 0) == nd)*/
    } /*if (f2py_success) of nd*/
    /* End of cleaning variable nd */
    } /*if (f2py_success) of xi*/
    /* End of cleaning variable xi */
    if((PyObject *)capi_xd_tmp!=xd_capi) {
        Py_XDECREF(capi_xd_tmp); }
    }  /*if (capi_xd_tmp == NULL) ... else of xd*/
    /* End of cleaning variable xd */
    /* End of cleaning variable r8vec_bracket5 */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*************************** end of r8vec_bracket5 ***************************/

/******************************* pwl_interp_2D *******************************/
static char doc_f2py_rout_genPosition_interp_pwl_interp_2D[] = "\
pwl_interp_2D(xd,yd,zd,xi,yi,zi,[nxd,nyd,ni])\n\nWrapper for ``pwl_interp_2D``.\
\n\nParameters\n----------\n"
"xd : input rank-1 array('d') with bounds (nxd)\n"
"yd : input rank-1 array('d') with bounds (nyd)\n"
"zd : input rank-2 array('d') with bounds (nxd,nyd)\n"
"xi : input rank-1 array('d') with bounds (ni)\n"
"yi : input rank-1 array('d') with bounds (ni)\n"
"zi : input rank-1 array('d') with bounds (ni)\n"
"\nOther Parameters\n----------------\n"
"nxd : input int, optional\n    Default: shape(xd, 0)\n"
"nyd : input int, optional\n    Default: shape(yd, 0)\n"
"ni : input int, optional\n    Default: shape(xi, 0)";
/*  */
static PyObject *f2py_rout_genPosition_interp_pwl_interp_2D(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,double*,double*,double*,int*,double*,double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int nxd = 0;
    PyObject *nxd_capi = Py_None;
    int nyd = 0;
    PyObject *nyd_capi = Py_None;
    double *xd = NULL;
    npy_intp xd_Dims[1] = {-1};
    const int xd_Rank = 1;
    PyArrayObject *capi_xd_tmp = NULL;
    int capi_xd_intent = 0;
    PyObject *xd_capi = Py_None;
    double *yd = NULL;
    npy_intp yd_Dims[1] = {-1};
    const int yd_Rank = 1;
    PyArrayObject *capi_yd_tmp = NULL;
    int capi_yd_intent = 0;
    PyObject *yd_capi = Py_None;
    double *zd = NULL;
    npy_intp zd_Dims[2] = {-1, -1};
    const int zd_Rank = 2;
    PyArrayObject *capi_zd_tmp = NULL;
    int capi_zd_intent = 0;
    PyObject *zd_capi = Py_None;
    int ni = 0;
    PyObject *ni_capi = Py_None;
    double *xi = NULL;
    npy_intp xi_Dims[1] = {-1};
    const int xi_Rank = 1;
    PyArrayObject *capi_xi_tmp = NULL;
    int capi_xi_intent = 0;
    PyObject *xi_capi = Py_None;
    double *yi = NULL;
    npy_intp yi_Dims[1] = {-1};
    const int yi_Rank = 1;
    PyArrayObject *capi_yi_tmp = NULL;
    int capi_yi_intent = 0;
    PyObject *yi_capi = Py_None;
    double *zi = NULL;
    npy_intp zi_Dims[1] = {-1};
    const int zi_Rank = 1;
    PyArrayObject *capi_zi_tmp = NULL;
    int capi_zi_intent = 0;
    PyObject *zi_capi = Py_None;
    static char *capi_kwlist[] = {"xd","yd","zd","xi","yi","zi","nxd","nyd","ni",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOO|OOO:genPosition.interp.pwl_interp_2D",\
        capi_kwlist,&xd_capi,&yd_capi,&zd_capi,&xi_capi,&yi_capi,&zi_capi,&nxd_capi,&nyd_capi,&ni_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable xd */
    ;
    capi_xd_intent |= F2PY_INTENT_IN;
    capi_xd_tmp = array_from_pyobj(NPY_DOUBLE,xd_Dims,xd_Rank,capi_xd_intent,xd_capi);
    if (capi_xd_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : genPosition_error,"failed in converting 1st argument `xd' of genPosition.interp.pwl_interp_2D to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        xd = (double *)(PyArray_DATA(capi_xd_tmp));

    /* Processing variable xi */
    ;
    capi_xi_intent |= F2PY_INTENT_IN;
    capi_xi_tmp = array_from_pyobj(NPY_DOUBLE,xi_Dims,xi_Rank,capi_xi_intent,xi_capi);
    if (capi_xi_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : genPosition_error,"failed in converting 4th argument `xi' of genPosition.interp.pwl_interp_2D to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        xi = (double *)(PyArray_DATA(capi_xi_tmp));

    /* Processing variable yd */
    ;
    capi_yd_intent |= F2PY_INTENT_IN;
    capi_yd_tmp = array_from_pyobj(NPY_DOUBLE,yd_Dims,yd_Rank,capi_yd_intent,yd_capi);
    if (capi_yd_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : genPosition_error,"failed in converting 2nd argument `yd' of genPosition.interp.pwl_interp_2D to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        yd = (double *)(PyArray_DATA(capi_yd_tmp));

    /* Processing variable ni */
    if (ni_capi == Py_None) ni = shape(xi, 0); else
        f2py_success = int_from_pyobj(&ni,ni_capi,"genPosition.interp.pwl_interp_2D() 3rd keyword (ni) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(xi, 0) == ni,"shape(xi, 0) == ni","3rd keyword ni","pwl_interp_2D:ni=%d",ni) {
    /* Processing variable nxd */
    if (nxd_capi == Py_None) nxd = shape(xd, 0); else
        f2py_success = int_from_pyobj(&nxd,nxd_capi,"genPosition.interp.pwl_interp_2D() 1st keyword (nxd) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(xd, 0) == nxd,"shape(xd, 0) == nxd","1st keyword nxd","pwl_interp_2D:nxd=%d",nxd) {
    /* Processing variable nyd */
    if (nyd_capi == Py_None) nyd = shape(yd, 0); else
        f2py_success = int_from_pyobj(&nyd,nyd_capi,"genPosition.interp.pwl_interp_2D() 2nd keyword (nyd) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(yd, 0) == nyd,"shape(yd, 0) == nyd","2nd keyword nyd","pwl_interp_2D:nyd=%d",nyd) {
    /* Processing variable yi */
    yi_Dims[0]=ni;
    capi_yi_intent |= F2PY_INTENT_IN;
    capi_yi_tmp = array_from_pyobj(NPY_DOUBLE,yi_Dims,yi_Rank,capi_yi_intent,yi_capi);
    if (capi_yi_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : genPosition_error,"failed in converting 5th argument `yi' of genPosition.interp.pwl_interp_2D to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        yi = (double *)(PyArray_DATA(capi_yi_tmp));

    /* Processing variable zd */
    zd_Dims[0]=nxd,zd_Dims[1]=nyd;
    capi_zd_intent |= F2PY_INTENT_IN;
    capi_zd_tmp = array_from_pyobj(NPY_DOUBLE,zd_Dims,zd_Rank,capi_zd_intent,zd_capi);
    if (capi_zd_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : genPosition_error,"failed in converting 3rd argument `zd' of genPosition.interp.pwl_interp_2D to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        zd = (double *)(PyArray_DATA(capi_zd_tmp));

    /* Processing variable zi */
    zi_Dims[0]=ni;
    capi_zi_intent |= F2PY_INTENT_IN;
    capi_zi_tmp = array_from_pyobj(NPY_DOUBLE,zi_Dims,zi_Rank,capi_zi_intent,zi_capi);
    if (capi_zi_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : genPosition_error,"failed in converting 6th argument `zi' of genPosition.interp.pwl_interp_2D to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        zi = (double *)(PyArray_DATA(capi_zi_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&nxd,&nyd,xd,yd,zd,&ni,xi,yi,zi);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_zi_tmp!=zi_capi) {
        Py_XDECREF(capi_zi_tmp); }
    }  /*if (capi_zi_tmp == NULL) ... else of zi*/
    /* End of cleaning variable zi */
    if((PyObject *)capi_zd_tmp!=zd_capi) {
        Py_XDECREF(capi_zd_tmp); }
    }  /*if (capi_zd_tmp == NULL) ... else of zd*/
    /* End of cleaning variable zd */
    if((PyObject *)capi_yi_tmp!=yi_capi) {
        Py_XDECREF(capi_yi_tmp); }
    }  /*if (capi_yi_tmp == NULL) ... else of yi*/
    /* End of cleaning variable yi */
    } /*CHECKSCALAR(shape(yd, 0) == nyd)*/
    } /*if (f2py_success) of nyd*/
    /* End of cleaning variable nyd */
    } /*CHECKSCALAR(shape(xd, 0) == nxd)*/
    } /*if (f2py_success) of nxd*/
    /* End of cleaning variable nxd */
    } /*CHECKSCALAR(shape(xi, 0) == ni)*/
    } /*if (f2py_success) of ni*/
    /* End of cleaning variable ni */
    if((PyObject *)capi_yd_tmp!=yd_capi) {
        Py_XDECREF(capi_yd_tmp); }
    }  /*if (capi_yd_tmp == NULL) ... else of yd*/
    /* End of cleaning variable yd */
    if((PyObject *)capi_xi_tmp!=xi_capi) {
        Py_XDECREF(capi_xi_tmp); }
    }  /*if (capi_xi_tmp == NULL) ... else of xi*/
    /* End of cleaning variable xi */
    if((PyObject *)capi_xd_tmp!=xd_capi) {
        Py_XDECREF(capi_xd_tmp); }
    }  /*if (capi_xd_tmp == NULL) ... else of xd*/
    /* End of cleaning variable xd */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/**************************** end of pwl_interp_2D ****************************/

/********************************* rk4Interp *********************************/
static char doc_f2py_rout_genPosition_integrate_rk4Interp[] = "\
rk4Interp(h,x,y,u,v,xi,yi,xx,yy,x_out,y_out,[Nint,velNI,velNJ,Np])\n\nWrapper for ``rk4Interp``.\
\n\nParameters\n----------\n"
"h : input float\n"
"x : input rank-1 array('d') with bounds (velNI)\n"
"y : input rank-1 array('d') with bounds (velNI)\n"
"u : input rank-2 array('d') with bounds (velNI,velNJ)\n"
"v : input rank-2 array('d') with bounds (velNI,velNJ)\n"
"xi : input rank-1 array('d') with bounds (Np)\n"
"yi : input rank-1 array('d') with bounds (Np)\n"
"xx : input rank-1 array('d') with bounds (Np)\n"
"yy : input rank-1 array('d') with bounds (Np)\n"
"x_out : input rank-2 array('d') with bounds (Np,Nint)\n"
"y_out : input rank-2 array('d') with bounds (Np,Nint)\n"
"\nOther Parameters\n----------------\n"
"Nint : input int, optional\n    Default: shape(x_out, 1)\n"
"velNI : input int, optional\n    Default: shape(x, 0)\n"
"velNJ : input int, optional\n    Default: shape(u, 1)\n"
"Np : input int, optional\n    Default: shape(xi, 0)";
/*  */
static PyObject *f2py_rout_genPosition_integrate_rk4Interp(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,int*,int*,double*,double*,double*,double*,int*,double*,double*,double*,double*,double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int Nint = 0;
    PyObject *Nint_capi = Py_None;
    double h = 0;
    PyObject *h_capi = Py_None;
    int velNI = 0;
    PyObject *velNI_capi = Py_None;
    int velNJ = 0;
    PyObject *velNJ_capi = Py_None;
    double *x = NULL;
    npy_intp x_Dims[1] = {-1};
    const int x_Rank = 1;
    PyArrayObject *capi_x_tmp = NULL;
    int capi_x_intent = 0;
    PyObject *x_capi = Py_None;
    double *y = NULL;
    npy_intp y_Dims[1] = {-1};
    const int y_Rank = 1;
    PyArrayObject *capi_y_tmp = NULL;
    int capi_y_intent = 0;
    PyObject *y_capi = Py_None;
    double *u = NULL;
    npy_intp u_Dims[2] = {-1, -1};
    const int u_Rank = 2;
    PyArrayObject *capi_u_tmp = NULL;
    int capi_u_intent = 0;
    PyObject *u_capi = Py_None;
    double *v = NULL;
    npy_intp v_Dims[2] = {-1, -1};
    const int v_Rank = 2;
    PyArrayObject *capi_v_tmp = NULL;
    int capi_v_intent = 0;
    PyObject *v_capi = Py_None;
    int Np = 0;
    PyObject *Np_capi = Py_None;
    double *xi = NULL;
    npy_intp xi_Dims[1] = {-1};
    const int xi_Rank = 1;
    PyArrayObject *capi_xi_tmp = NULL;
    int capi_xi_intent = 0;
    PyObject *xi_capi = Py_None;
    double *yi = NULL;
    npy_intp yi_Dims[1] = {-1};
    const int yi_Rank = 1;
    PyArrayObject *capi_yi_tmp = NULL;
    int capi_yi_intent = 0;
    PyObject *yi_capi = Py_None;
    double *xx = NULL;
    npy_intp xx_Dims[1] = {-1};
    const int xx_Rank = 1;
    PyArrayObject *capi_xx_tmp = NULL;
    int capi_xx_intent = 0;
    PyObject *xx_capi = Py_None;
    double *yy = NULL;
    npy_intp yy_Dims[1] = {-1};
    const int yy_Rank = 1;
    PyArrayObject *capi_yy_tmp = NULL;
    int capi_yy_intent = 0;
    PyObject *yy_capi = Py_None;
    double *x_out = NULL;
    npy_intp x_out_Dims[2] = {-1, -1};
    const int x_out_Rank = 2;
    PyArrayObject *capi_x_out_tmp = NULL;
    int capi_x_out_intent = 0;
    PyObject *x_out_capi = Py_None;
    double *y_out = NULL;
    npy_intp y_out_Dims[2] = {-1, -1};
    const int y_out_Rank = 2;
    PyArrayObject *capi_y_out_tmp = NULL;
    int capi_y_out_intent = 0;
    PyObject *y_out_capi = Py_None;
    static char *capi_kwlist[] = {"h","x","y","u","v","xi","yi","xx","yy","x_out","y_out","Nint","velNI","velNJ","Np",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOOOOO|OOOO:genPosition.integrate.rk4Interp",\
        capi_kwlist,&h_capi,&x_capi,&y_capi,&u_capi,&v_capi,&xi_capi,&yi_capi,&xx_capi,&yy_capi,&x_out_capi,&y_out_capi,&Nint_capi,&velNI_capi,&velNJ_capi,&Np_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable h */
        f2py_success = double_from_pyobj(&h,h_capi,"genPosition.integrate.rk4Interp() 1st argument (h) can't be converted to double");
    if (f2py_success) {
    /* Processing variable xi */
    ;
    capi_xi_intent |= F2PY_INTENT_IN;
    capi_xi_tmp = array_from_pyobj(NPY_DOUBLE,xi_Dims,xi_Rank,capi_xi_intent,xi_capi);
    if (capi_xi_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : genPosition_error,"failed in converting 6th argument `xi' of genPosition.integrate.rk4Interp to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        xi = (double *)(PyArray_DATA(capi_xi_tmp));

    /* Processing variable x */
    ;
    capi_x_intent |= F2PY_INTENT_IN;
    capi_x_tmp = array_from_pyobj(NPY_DOUBLE,x_Dims,x_Rank,capi_x_intent,x_capi);
    if (capi_x_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : genPosition_error,"failed in converting 2nd argument `x' of genPosition.integrate.rk4Interp to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        x = (double *)(PyArray_DATA(capi_x_tmp));

    /* Processing variable velNI */
    if (velNI_capi == Py_None) velNI = shape(x, 0); else
        f2py_success = int_from_pyobj(&velNI,velNI_capi,"genPosition.integrate.rk4Interp() 2nd keyword (velNI) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(x, 0) == velNI,"shape(x, 0) == velNI","2nd keyword velNI","rk4Interp:velNI=%d",velNI) {
    /* Processing variable Np */
    if (Np_capi == Py_None) Np = shape(xi, 0); else
        f2py_success = int_from_pyobj(&Np,Np_capi,"genPosition.integrate.rk4Interp() 4th keyword (Np) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(xi, 0) == Np,"shape(xi, 0) == Np","4th keyword Np","rk4Interp:Np=%d",Np) {
    /* Processing variable yi */
    yi_Dims[0]=Np;
    capi_yi_intent |= F2PY_INTENT_IN;
    capi_yi_tmp = array_from_pyobj(NPY_DOUBLE,yi_Dims,yi_Rank,capi_yi_intent,yi_capi);
    if (capi_yi_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : genPosition_error,"failed in converting 7th argument `yi' of genPosition.integrate.rk4Interp to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        yi = (double *)(PyArray_DATA(capi_yi_tmp));

    /* Processing variable xx */
    xx_Dims[0]=Np;
    capi_xx_intent |= F2PY_INTENT_IN;
    capi_xx_tmp = array_from_pyobj(NPY_DOUBLE,xx_Dims,xx_Rank,capi_xx_intent,xx_capi);
    if (capi_xx_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : genPosition_error,"failed in converting 8th argument `xx' of genPosition.integrate.rk4Interp to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        xx = (double *)(PyArray_DATA(capi_xx_tmp));

    /* Processing variable yy */
    yy_Dims[0]=Np;
    capi_yy_intent |= F2PY_INTENT_IN;
    capi_yy_tmp = array_from_pyobj(NPY_DOUBLE,yy_Dims,yy_Rank,capi_yy_intent,yy_capi);
    if (capi_yy_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : genPosition_error,"failed in converting 9th argument `yy' of genPosition.integrate.rk4Interp to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        yy = (double *)(PyArray_DATA(capi_yy_tmp));

    /* Processing variable y */
    y_Dims[0]=velNI;
    capi_y_intent |= F2PY_INTENT_IN;
    capi_y_tmp = array_from_pyobj(NPY_DOUBLE,y_Dims,y_Rank,capi_y_intent,y_capi);
    if (capi_y_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : genPosition_error,"failed in converting 3rd argument `y' of genPosition.integrate.rk4Interp to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        y = (double *)(PyArray_DATA(capi_y_tmp));

    /* Processing variable u */
    u_Dims[0]=velNI;
    capi_u_intent |= F2PY_INTENT_IN;
    capi_u_tmp = array_from_pyobj(NPY_DOUBLE,u_Dims,u_Rank,capi_u_intent,u_capi);
    if (capi_u_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : genPosition_error,"failed in converting 4th argument `u' of genPosition.integrate.rk4Interp to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        u = (double *)(PyArray_DATA(capi_u_tmp));

    /* Processing variable x_out */
    x_out_Dims[0]=Np;
    capi_x_out_intent |= F2PY_INTENT_IN;
    capi_x_out_tmp = array_from_pyobj(NPY_DOUBLE,x_out_Dims,x_out_Rank,capi_x_out_intent,x_out_capi);
    if (capi_x_out_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : genPosition_error,"failed in converting 10th argument `x_out' of genPosition.integrate.rk4Interp to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        x_out = (double *)(PyArray_DATA(capi_x_out_tmp));

    /* Processing variable velNJ */
    if (velNJ_capi == Py_None) velNJ = shape(u, 1); else
        f2py_success = int_from_pyobj(&velNJ,velNJ_capi,"genPosition.integrate.rk4Interp() 3rd keyword (velNJ) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(u, 1) == velNJ,"shape(u, 1) == velNJ","3rd keyword velNJ","rk4Interp:velNJ=%d",velNJ) {
    /* Processing variable Nint */
    if (Nint_capi == Py_None) Nint = shape(x_out, 1); else
        f2py_success = int_from_pyobj(&Nint,Nint_capi,"genPosition.integrate.rk4Interp() 1st keyword (Nint) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(x_out, 1) == Nint,"shape(x_out, 1) == Nint","1st keyword Nint","rk4Interp:Nint=%d",Nint) {
    /* Processing variable v */
    v_Dims[0]=velNI,v_Dims[1]=velNJ;
    capi_v_intent |= F2PY_INTENT_IN;
    capi_v_tmp = array_from_pyobj(NPY_DOUBLE,v_Dims,v_Rank,capi_v_intent,v_capi);
    if (capi_v_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : genPosition_error,"failed in converting 5th argument `v' of genPosition.integrate.rk4Interp to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        v = (double *)(PyArray_DATA(capi_v_tmp));

    /* Processing variable y_out */
    y_out_Dims[0]=Np,y_out_Dims[1]=Nint;
    capi_y_out_intent |= F2PY_INTENT_IN;
    capi_y_out_tmp = array_from_pyobj(NPY_DOUBLE,y_out_Dims,y_out_Rank,capi_y_out_intent,y_out_capi);
    if (capi_y_out_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : genPosition_error,"failed in converting 11st argument `y_out' of genPosition.integrate.rk4Interp to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        y_out = (double *)(PyArray_DATA(capi_y_out_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&Nint,&h,&velNI,&velNJ,x,y,u,v,&Np,xi,yi,xx,yy,x_out,y_out);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_y_out_tmp!=y_out_capi) {
        Py_XDECREF(capi_y_out_tmp); }
    }  /*if (capi_y_out_tmp == NULL) ... else of y_out*/
    /* End of cleaning variable y_out */
    if((PyObject *)capi_v_tmp!=v_capi) {
        Py_XDECREF(capi_v_tmp); }
    }  /*if (capi_v_tmp == NULL) ... else of v*/
    /* End of cleaning variable v */
    } /*CHECKSCALAR(shape(x_out, 1) == Nint)*/
    } /*if (f2py_success) of Nint*/
    /* End of cleaning variable Nint */
    } /*CHECKSCALAR(shape(u, 1) == velNJ)*/
    } /*if (f2py_success) of velNJ*/
    /* End of cleaning variable velNJ */
    if((PyObject *)capi_x_out_tmp!=x_out_capi) {
        Py_XDECREF(capi_x_out_tmp); }
    }  /*if (capi_x_out_tmp == NULL) ... else of x_out*/
    /* End of cleaning variable x_out */
    if((PyObject *)capi_u_tmp!=u_capi) {
        Py_XDECREF(capi_u_tmp); }
    }  /*if (capi_u_tmp == NULL) ... else of u*/
    /* End of cleaning variable u */
    if((PyObject *)capi_y_tmp!=y_capi) {
        Py_XDECREF(capi_y_tmp); }
    }  /*if (capi_y_tmp == NULL) ... else of y*/
    /* End of cleaning variable y */
    if((PyObject *)capi_yy_tmp!=yy_capi) {
        Py_XDECREF(capi_yy_tmp); }
    }  /*if (capi_yy_tmp == NULL) ... else of yy*/
    /* End of cleaning variable yy */
    if((PyObject *)capi_xx_tmp!=xx_capi) {
        Py_XDECREF(capi_xx_tmp); }
    }  /*if (capi_xx_tmp == NULL) ... else of xx*/
    /* End of cleaning variable xx */
    if((PyObject *)capi_yi_tmp!=yi_capi) {
        Py_XDECREF(capi_yi_tmp); }
    }  /*if (capi_yi_tmp == NULL) ... else of yi*/
    /* End of cleaning variable yi */
    } /*CHECKSCALAR(shape(xi, 0) == Np)*/
    } /*if (f2py_success) of Np*/
    /* End of cleaning variable Np */
    } /*CHECKSCALAR(shape(x, 0) == velNI)*/
    } /*if (f2py_success) of velNI*/
    /* End of cleaning variable velNI */
    if((PyObject *)capi_x_tmp!=x_capi) {
        Py_XDECREF(capi_x_tmp); }
    }  /*if (capi_x_tmp == NULL) ... else of x*/
    /* End of cleaning variable x */
    if((PyObject *)capi_xi_tmp!=xi_capi) {
        Py_XDECREF(capi_xi_tmp); }
    }  /*if (capi_xi_tmp == NULL) ... else of xi*/
    /* End of cleaning variable xi */
    } /*if (f2py_success) of h*/
    /* End of cleaning variable h */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of rk4Interp ******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/

static FortranDataDef f2py_arrays_def[] = {
  {"r8vec_linspace",-1,{{-1}},0,NULL,(void *)f2py_rout_genPosition_arrays_r8vec_linspace,doc_f2py_rout_genPosition_arrays_r8vec_linspace},
  {NULL}
};

static void f2py_setup_arrays(char *r8vec_linspace) {
  int i_f2py=0;
  f2py_arrays_def[i_f2py++].data = r8vec_linspace;
}
extern void F_FUNC(f2pyinitarrays,F2PYINITARRAYS)(void (*)(char *));
static void f2py_init_arrays(void) {
  F_FUNC(f2pyinitarrays,F2PYINITARRAYS)(f2py_setup_arrays);
}


static FortranDataDef f2py_interp_def[] = {
  {"r8_huge",-1,{{-1}},0,NULL,(void *)f2py_rout_genPosition_interp_r8_huge,doc_f2py_rout_genPosition_interp_r8_huge},
  {"r8vec_bracket5",-1,{{-1}},0,NULL,(void *)f2py_rout_genPosition_interp_r8vec_bracket5,doc_f2py_rout_genPosition_interp_r8vec_bracket5},
  {"pwl_interp_2D",-1,{{-1}},0,NULL,(void *)f2py_rout_genPosition_interp_pwl_interp_2D,doc_f2py_rout_genPosition_interp_pwl_interp_2D},
  {NULL}
};

static void f2py_setup_interp(char *r8_huge,char *r8vec_bracket5,char *pwl_interp_2D) {
  int i_f2py=0;
  f2py_interp_def[i_f2py++].data = r8_huge;
  f2py_interp_def[i_f2py++].data = r8vec_bracket5;
  f2py_interp_def[i_f2py++].data = pwl_interp_2D;
}
extern void F_FUNC(f2pyinitinterp,F2PYINITINTERP)(void (*)(char *,char *,char *));
static void f2py_init_interp(void) {
  F_FUNC(f2pyinitinterp,F2PYINITINTERP)(f2py_setup_interp);
}


static FortranDataDef f2py_integrate_def[] = {
  {"rk4Interp",-1,{{-1}},0,NULL,(void *)f2py_rout_genPosition_integrate_rk4Interp,doc_f2py_rout_genPosition_integrate_rk4Interp},
  {NULL}
};

static void f2py_setup_integrate(char *rk4Interp) {
  int i_f2py=0;
  f2py_integrate_def[i_f2py++].data = rk4Interp;
}
extern void F_FUNC(f2pyinitintegrate,F2PYINITINTEGRATE)(void (*)(char *));
static void f2py_init_integrate(void) {
  F_FUNC(f2pyinitintegrate,F2PYINITINTEGRATE)(f2py_setup_integrate);
}

/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"main",-1,{{-1}},0,(char *)F_WRAPPEDFUNC(main,MAIN),(f2py_init_func)f2py_rout_genPosition_main,doc_f2py_rout_genPosition_main},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "genPosition",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit_genPosition(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = genPosition_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module genPosition (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("1.22.4");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module 'genPosition' is auto-generated with f2py (version:1.22.4).\nFunctions:\n"
"    x_out,y_out = main(N,Np,Nint,u,v,xi,yi)\n"
"Fortran 90/95 modules:\n""  arrays --- r8vec_linspace()""  interp --- r8_huge(),r8vec_bracket5(),pwl_interp_2D()""  integrate --- rk4Interp()"".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("1.22.4");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    genPosition_error = PyErr_NewException ("genPosition.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "_genPosition_error", genPosition_error);
    Py_DECREF(genPosition_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }

    {
      extern void F_FUNC(main,MAIN)(void);
      PyObject* o = PyDict_GetItemString(d,"main");
      tmp = F2PyCapsule_FromVoidPtr((void*)F_FUNC(main,MAIN),NULL);
      PyObject_SetAttrString(o,"_cpointer", tmp);
      Py_DECREF(tmp);
      s = PyUnicode_FromString("main");
      PyObject_SetAttrString(o,"__name__", s);
      Py_DECREF(s);
    }
    





/*eof initf2pywraphooks*/
  PyDict_SetItemString(d, "integrate", PyFortranObject_New(f2py_integrate_def,f2py_init_integrate));
  PyDict_SetItemString(d, "interp", PyFortranObject_New(f2py_interp_def,f2py_init_interp));
  PyDict_SetItemString(d, "arrays", PyFortranObject_New(f2py_arrays_def,f2py_init_arrays));
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"genPosition");
#endif
    return m;
}
#ifdef __cplusplus
}
#endif
